# Generated by Django 3.1 on 2021-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncType', models.CharField(choices=[(1, 'Int.'), (2, 'Prop.')], max_length=255, null=True)),
                ('lboxSamples', models.CharField(choices=[('', 'Choose...'), ('MG', 'Minas Gerais'), ('SP', 'Sao Paulo'), ('RJ', 'Rio de Janeiro')], max_length=255, null=True)),
            ],
        ),
    ]
